# Generated by Django 4.1.7 on 2023-03-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_careercenter_coordinator_student_practise'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractiseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Under Review'), (1, 'Approved'), (2, 'Disprove')])),
                ('uploaded_form', models.FileField(blank=True, null=True, upload_to='submissions')),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
