# Generated by Django 4.1.7 on 2023-03-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_practise_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practisesubmission',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Approved'), (0, 'Under Review'), (2, 'Disprove')]),
        ),
    ]
