# Generated by Django 4.1.7 on 2023-03-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_practisesubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practisesubmission',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Approved'), (2, 'Disprove'), (0, 'Under Review')]),
        ),
    ]
